export const EventList = [
  {
    id: 1,
    category: "mazemarize",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "mazemarize",
    eventcoordinators: [
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event lead",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "Swagata Khuntia",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1EO_VCTK_ptV1L89Akys2qSmsv5coos6I",
        position: "event coordinator",
        phone: "9907144797",
        dept: "ECE",
        year: "3rd",
        email: "swagatakhuntia2003@gmail.com",
        isReverse: true,
      },
      {
        name: "Dip Roy ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1lFesSzXCwwQfqOkyal2WqKRmeqEdOmlP",
        position: "event coordinator",
        phone: "9749021886",
        dept: "ME",
        year: "3rd",
        email: "dipp713146@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "auditorium hall",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/mazemarize/register",
    leaderboard: "/events/mazemarize/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 2,
    category: "roboSoccer",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "robo Soccer",
    eventcoordinators: [
      {
        name: "Asanka Maiti",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1YhbJfZZLYTwjsEEW0SWnLRpExiPDZkyb",
        position: "event lead",
        phone: "7797307847",
        dept: "ECE",
        year: "3rd",
        email: "asankamaiti111@gmail.com",
        isReverse: false,
      },
      {
        name: "Amit Maiti ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1MTu3In2RGMc24Xxban7gdcS8TqvGYRt-",
        position: "event coordinator",
        phone: "9749427693",
        dept: "ECE",
        year: "3rd",
        email: "amitmaiti2003@gmail.com",
        isReverse: true,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ECE",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "auditoriam hall",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/roboSoccer/register",
    leaderboard: "/events/roboSoccer/leaderboard",
    prizes: [8000, 5000, 3000],
  },
  {
    id: 3,
    category: "sputnik",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "sputnik",
    eventcoordinators: [
      {
        name: "Taibu roy ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1h7U9nBgi9bilbKCgg1S4kvFX3fx9IOAS",
        position: "event lead",
        phone: "9883482136",
        dept: "ME",
        year: "3rd",
        email: "taiburay27@gmail.com",
        isReverse: false,
      },
      {
        name: "Soumen mallick",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1YkBszyMYJhCEKLkgF40rF18yOE-wdj-M",
        position: "event coordinator",
        phone: "7478552309",
        dept: "ECE",
        year: "3rd",
        email: "sonaimallick765@gmail.com",
        isReverse: true,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1SDP4-RQbVeshsQbxe4Uyii-VetTBLSZe",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "oval ground",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sputnik/register",
    leaderboard: "/events/sputnik/leaderboard",
    prizes: [5000, 3000, 2000],
  },
  {
    id: 4,
    category: "rotolare",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "rotolare",
    eventcoordinators: [
      {
        name: "Om Kumar Sah",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1Kj_P1PXqUQ_cE0r5LfEh9k-axXICYVVx",
        position: "event lead",
        phone: "6290889507",
        dept: "CE",
        year: "3rd",
        email: "ok2508@ce.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Aditi Pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1VtYK_5WGuhfLC_W4_NrtZ7xGZ0yicEbX/view",
        position: "event coordinator",
        phone: "8902797178",
        dept: "CE",
        year: "3rd",
        email: "ap2530@ce.jgec.ac.in",
        isReverse: true,
      },
      {
        name: "Malay Poulik ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1AdNy96trAS7Aqe2anTo0REm9kh_nVsPh",
        position: "event coordinator",
        phone: "7679185576",
        dept: "CE",
        year: "3rd",
        email: "malaypoulik252@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "auditorium hall",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/rotolare/register",
    leaderboard: "/events/rotolare/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 5,
    category: "bridgeTheGap",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "bridge The Gap",
    eventcoordinators: [
      {
        name: "Akash Kumar layek ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1Sa_ZDdVE-HKqad6CuowC0mwsrcu95-Mn",
        position: "event lead",
        phone: "7797672846",
        dept: "CE",
        year: "3rd",
        email: "ak2563@ce.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Mahek Parvez",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1gVVVeDZtgMJYUATtR777VvJ5oHLsLqPo",
        position: "event coordinator",
        dept: "CE",
        year: "3rd",
        email: "mp2555@ce.jgec.ac.in",
        isReverse: true,
      },
      {
        name: "Sourav Ganguly",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1iGxt9tkZnsDSpx02zdOipM-C7gokBCyB",
        position: "event coordinator",
        phone: "8918798847",
        dept: "CE",
        year: "3rd",
        email: "sg2525@ce.jgec.ac.in",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "auditorium hall",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/bridgeTheGap/register",
    leaderboard: "/events/bridgeTheGap/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 6,
    category: "codeChronicles",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "code Chronicles",
    eventcoordinators: [
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event lead",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "DR1 Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/codeChronicles/register",
    leaderboard: "/events/codeChronicles/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 7,
    category: "cssBattle",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "css Battle",
    eventcoordinators: [
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event lead",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "Siddharth Biswas",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=11fFWkKoLVXk6i-pw1r8mqAgd0aZXa9ur",
        position: "event coordinator",
        phone: "6291369741",
        dept: "IT",
        year: "3rd",
        email: "siddharth211102@gmail.com",
        isReverse: true,
      },
      {
        name: "Aishik Patra",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1dBRD3ZqFctLiDvMcldg11k1Jnr8xVj88",
        position: "event coordinator",
        phone: "7602989174",
        dept: "IT",
        year: "3rd",
        email: "ap2557@it.jgec.ac.in",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "DR1 Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/cssBattle/register",
    leaderboard: "/events/cssBattle/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 8,
    category: "captureTheFlag",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "capture The Flag",
    eventcoordinators: [
      {
        name: "Pankaj Barman ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1C6gI1ToLCqCyfRqbL0xRqJBrOY8yNUCy",
        position: "event lead",
        phone: "8101480752",
        dept: "CSE",
        year: "3rd",
        email: "pb2538@cse.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Sandipan Chatterjee",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1FGimIoX-cl-pUjwsi_161qKZEFd2ot2t",
        position: "event coordinator",
        phone: "8258977597",
        dept: "CSE",
        year: "3rd",
        email: "sandipan3002@gmail.com",
        isReverse: true,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "DR1 Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/captureTheFlag/register",
    leaderboard: "/events/captureTheFlag/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 9,
    category: "sharkTankJolu",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "shark Tank Jolu",
    eventcoordinators: [
      {
        name: "Adrita Mandal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1jdy-f7Qw7TQj4BA945jEOzv2F8zFTARx",
        position: "event lead",
        phone: "9679953824",
        dept: "IT",
        year: "3rd",
        email: "mandaladrita8@gmail.com",
        isReverse: false,
      },
      {
        name: "Rohini Afsana",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1OKlcVhCLJzDa0xgnvkdVom3r5t_ZNYIq",
        position: "event coordinator",
        phone: "7983216103",
        dept: "EE",
        year: "3rd",
        email: "ra2554@ee.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sharkTankJolu/register",
    leaderboard: "/events/sharkTankJolu/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 10,
    category: "jBuzz",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "j Buzz",
    eventcoordinators: [
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event lead",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/jBuzz/register",
    leaderboard: "/events/jBuzz/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 11,
    category: "sharkTankJolu",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "shark Tank Jolu",
    eventcoordinators: [
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event lead",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sharkTankJolu/register",
    leaderboard: "/events/sharkTankJolu/leaderboard",
    prizes: [5000, 2000, 1000],
  },
];
