import { eventCoordinatorSchema,EventData } from "../events/[eventname]/page";

export const EventList: EventData[] = [
  {
    id: 1,
    category: "mazemarize",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "mazemarize",
    eventCoordinators: [
      {
        name: "Rajat Nandi",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=12Lo2MgxKilOd5T_q8RIcG5oXVXI6ui0B",
        position: "event lead",
        phone: "8900352943",
        dept: "ECE",
        year: "3rd",
        email: "rn25252@ece.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Swagata Khuntia",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1EO_VCTK_ptV1L89Akys2qSmsv5coos6I",
        position: "event coordinator",
        phone: "9907144797",
        dept: "ECE",
        year: "3rd",
        email: "swagatakhuntia2003@gmail.com",
        isReverse: true,
      },
      {
        name: "Dip Roy ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1lFesSzXCwwQfqOkyal2WqKRmeqEdOmlP",
        position: "event coordinator",
        phone: "9749021886",
        dept: "ME",
        year: "3rd",
        email: "dipp713146@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "auditorium hall",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/mazemarize/register",
    leaderboard: "/events/mazemarize/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 2,
    category: "roboSoccer",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "robo Soccer",
    eventCoordinators: [
      {
        name: "Asanka Maiti",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1YhbJfZZLYTwjsEEW0SWnLRpExiPDZkyb",
        position: "event lead",
        phone: "7797307847",
        dept: "ECE",
        year: "3rd",
        email: "asankamaiti111@gmail.com",
        isReverse: false,
      },
      {
        name: "Amit Maiti ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1MTu3In2RGMc24Xxban7gdcS8TqvGYRt-",
        position: "event coordinator",
        phone: "9749427693",
        dept: "ECE",
        year: "3rd",
        email: "amitmaiti2003@gmail.com",
        isReverse: true,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ECE",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "auditoriam hall",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/roboSoccer/register",
    leaderboard: "/events/roboSoccer/leaderboard",
    prizes: [8000, 5000, 3000],
  },
  {
    id: 3,
    category: "sputnik",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "sputnik",
    eventCoordinators: [
      {
        name: "Taibu roy ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1h7U9nBgi9bilbKCgg1S4kvFX3fx9IOAS",
        position: "event lead",
        phone: "9883482136",
        dept: "ME",
        year: "3rd",
        email: "taiburay27@gmail.com",
        isReverse: false,
      },
      {
        name: "Soumen mallick",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1YkBszyMYJhCEKLkgF40rF18yOE-wdj-M",
        position: "event coordinator",
        phone: "7478552309",
        dept: "ECE",
        year: "3rd",
        email: "sonaimallick765@gmail.com",
        isReverse: true,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1SDP4-RQbVeshsQbxe4Uyii-VetTBLSZe",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "oval ground",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sputnik/register",
    leaderboard: "/events/sputnik/leaderboard",
    prizes: [5000, 3000, 2000],
  },
  {
    id: 4,
    category: "rotolare",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "rotolare",
    eventCoordinators: [
      {
        name: "Om Kumar Sah",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1Kj_P1PXqUQ_cE0r5LfEh9k-axXICYVVx",
        position: "event lead",
        phone: "6290889507",
        dept: "CE",
        year: "3rd",
        email: "ok2508@ce.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Aditi Pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1VtYK_5WGuhfLC_W4_NrtZ7xGZ0yicEbX/view",
        position: "event coordinator",
        phone: "8902797178",
        dept: "CE",
        year: "3rd",
        email: "ap2530@ce.jgec.ac.in",
        isReverse: true,
      },
      {
        name: "Malay Poulik ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1AdNy96trAS7Aqe2anTo0REm9kh_nVsPh",
        position: "event coordinator",
        phone: "7679185576",
        dept: "CE",
        year: "3rd",
        email: "malaypoulik252@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "auditorium hall",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/rotolare/register",
    leaderboard: "/events/rotolare/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 5,
    category: "bridgeTheGap",
    rules: [
      "Bridge should be with in the specific range of height and length , which will be specified before the event.",
      "The Bridge must have to be a suspension bridge .",
      "Winner will be decided on the basis of load carrying capacity of their bridge ",
      "Event is open to all",
      "Maximum team size is 5",
      "Participants can form teams from different branches/ college/ university/institute.",
      "No two teams must have any common member.",
      "The time limit for the completion is (will be declared soon) hours.",
      "The decision of the judges shall be final.",
    ],
    name: "bridge The Gap",
    eventCoordinators: [
      {
        name: "Akash Kumar layek ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1Sa_ZDdVE-HKqad6CuowC0mwsrcu95-Mn",
        position: "event lead",
        phone: "7797672846",
        dept: "CE",
        year: "3rd",
        email: "ak2563@ce.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Mahek Parvez",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1gVVVeDZtgMJYUATtR777VvJ5oHLsLqPo",
        position: "event coordinator",
        phone: "8597530118",
        dept: "CE",
        year: "3rd",
        email: "mp2555@ce.jgec.ac.in",
        isReverse: true,
      },
      {
        name: "Sourav Ganguly",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1iGxt9tkZnsDSpx02zdOipM-C7gokBCyB",
        position: "event coordinator",
        phone: "8918798847",
        dept: "CE",
        year: "3rd",
        email: "sg2525@ce.jgec.ac.in",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "auditorium hall",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/bridgeTheGap/register",
    leaderboard: "/events/bridgeTheGap/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 6,
    category: "codeChronicles",
    rules: [
      "3 CP Questions  in prelims",
      "5 CP Questions in prelims",
      "Top 20%* will qualify for finals",
      "5 CP Questions in final round",
      "2 hours in final round",
    ],
    name: "code Chronicles",
    eventCoordinators: [
      {
        name: "Spandan Bhattacharya",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=15aT6ylFzNqcxcUk-lQpiW1xKG8In3r3U",
        position: "event lead",
        phone: "9330184706",
        dept: "CSE",
        year: "3rd",
        email: "spandanbhattacharya.sb@gmail.com",
        isReverse: false,
      },
      {
        name: "Animesh Bag ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1fGNdI48aOF9YBEhG1pWvYP7wxUvJ5laM",
        position: "event coordinator",
        phone: "6297733147",
        dept: "CSE",
        year: "3rd",
        email: "animeshbag606@gmail.com",
        isReverse: true,
      },
      {
        name: "Sucil dey",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "DR1 Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/codeChronicles/register",
    leaderboard: "/events/codeChronicles/leaderboard",
    prizes: [1723, 1024, 576],
  },
  {
    id: 7,
    category: "cssBattle",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "css Battle",
    eventCoordinators: [
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event lead",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "Siddharth Biswas",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=11fFWkKoLVXk6i-pw1r8mqAgd0aZXa9ur",
        position: "event coordinator",
        phone: "6291369741",
        dept: "IT",
        year: "3rd",
        email: "siddharth211102@gmail.com",
        isReverse: true,
      },
      {
        name: "Aishik Patra",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1dBRD3ZqFctLiDvMcldg11k1Jnr8xVj88",
        position: "event coordinator",
        phone: "7602989174",
        dept: "IT",
        year: "3rd",
        email: "ap2557@it.jgec.ac.in",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "DR1 Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/cssBattle/register",
    leaderboard: "/events/cssBattle/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 8,
    category: "captureTheFlag",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "capture The Flag",
    eventCoordinators: [
      {
        name: "Pankaj Barman ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1C6gI1ToLCqCyfRqbL0xRqJBrOY8yNUCy",
        position: "event lead",
        phone: "8101480752",
        dept: "CSE",
        year: "3rd",
        email: "pb2538@cse.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Sandipan Chatterjee",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1FGimIoX-cl-pUjwsi_161qKZEFd2ot2t",
        position: "event coordinator",
        phone: "8258977597",
        dept: "CSE",
        year: "3rd",
        email: "sandipan3002@gmail.com",
        isReverse: true,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "DR1 Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/captureTheFlag/register",
    leaderboard: "/events/captureTheFlag/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 9,
    category: "sharkTankJolu",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "shark Tank Jolu",
    eventCoordinators: [
      {
        name: "Adrita Mandal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1jdy-f7Qw7TQj4BA945jEOzv2F8zFTARx",
        position: "event lead",
        phone: "9679953824",
        dept: "IT",
        year: "3rd",
        email: "mandaladrita8@gmail.com",
        isReverse: false,
      },
      {
        name: "Rohini Afsana",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1OKlcVhCLJzDa0xgnvkdVom3r5t_ZNYIq",
        position: "event coordinator",
        phone: "7983216103",
        dept: "EE",
        year: "3rd",
        email: "ra2554@ee.jgec.ac.in",
        isReverse: true,
      },
      {
        name: "Debraat halder",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1GB1O03PDY6KgDSRuZnHsY6Cv2Ls7hFfe",
        position: "event coordinator",
        phone: "8967903389",
        dept: "CE",
        year: "3rd",
        email: "debraathalder69@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sharkTankJolu/register",
    leaderboard: "/events/sharkTankJolu/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 10,
    category: "jBuzz",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "j Buzz",
    eventCoordinators: [
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event lead",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
      {
        name: "swadesh pal",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=16ewsRuD_8FxK9amOpru16QOeEcizbVer",
        position: "event coordinator",
        phone: "8436893969",
        dept: "ME",
        year: "3rd",
        email: "swadeshpal129@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/jBuzz/register",
    leaderboard: "/events/jBuzz/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 11,
    category: "modelParliament",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "Model Parliament",
    eventCoordinators: [
      {
        name: "Aditi kumari",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1tVS3hZoghEDW1_d-irpgSDyI9gCKAbn6",
        position: "event lead",
        phone: "7407570466",
        dept: "IT",
        year: "3rd",
        email: "123aditi.kr@gmail.com",
        isReverse: false,
      },
      {
        name: "Rohini Afsana",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1OKlcVhCLJzDa0xgnvkdVom3r5t_ZNYIq",
        position: "event coordinator",
        phone: "7983216103",
        dept: "EE",
        year: "3rd",
        email: "ra2554@ee.jgec.ac.in",
        isReverse: true,
      },
      {
        name: "Sumit Mazumdar ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1v9WvPDeTEOR-uTXPy-_PopplvAaqHzNQ",
        position: "event coordinator",
        phone: "7739164949",
        dept: "CE",
        year: "3rd",
        email: "sm2512@ce.jgec.ac.in",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sharkTankJolu/register",
    leaderboard: "/events/sharkTankJolu/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 12,
    category: "caseStudy",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "Case Study",
    eventCoordinators: [
      {
        name: "Aditi kumari",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1tVS3hZoghEDW1_d-irpgSDyI9gCKAbn6",
        position: "event lead",
        phone: "7407570466",
        dept: "IT",
        year: "3rd",
        email: "123aditi.kr@gmail.com",
        isReverse: false,
      },
      {
        name: "Shreyashi Dasgupta",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1uRSJRf62sUYtYxIR4FV56WlaCZuwB6gW",
        position: "event coordinator",
        phone: "8327842765",
        dept: "EE",
        year: "3rd",
        email: "shreyashidasgupta.apdj@gmail.com",
        isReverse: true,
      },
      {
        name: "Shreyan Majumdar",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1cXOaYMYB5yEI16cuuIF5qW8zERFTrBhE",
        position: "event coordinator",
        phone: "7797152845",
        dept: "CSE",
        year: "3rd",
        email: "shreyanjalpaiguri@gmail.com",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sharkTankJolu/register",
    leaderboard: "/events/sharkTankJolu/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 13,
    category: "troubleshooter",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "Troubleshooter",
    eventCoordinators: [
      {
        name: "Shreya Dandapat",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1lpieo-tBY5SAK0zgRfVsYc0-IKtYmSzh",
        position: "event lead",
        phone: "8847850725",
        dept: "ME",
        year: "3rd",
        email: "sd2564@me.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Riddhiman Tarafder ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1RsW0a4fwV0xTH--voF8tGEL_QwpVuWrs",
        position: "event coordinator",
        phone: "7384597900",
        dept: "ECE",
        year: "3rd",
        email: "rt2505@ece.jgec.ac.in",
        isReverse: true,
      },
      {
        name: "Shreya Dandapat",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1lpieo-tBY5SAK0zgRfVsYc0-IKtYmSzh",
        position: "event coordinator",
        phone: "8847850725",
        dept: "ME",
        year: "3rd",
        email: "sd2564@me.jgec.ac.in",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sharkTankJolu/register",
    leaderboard: "/events/sharkTankJolu/leaderboard",
    prizes: [5000, 2000, 1000],
  },
  {
    id: 13,
    category: "techzibition",
    rules: [
      "sdafsdfsdafasdflasdjkhfasdfhasdhjkflsadfhasdffas sdffasdfasdf dsafasdfasfasd afasdfsdafsda asdfasf",
      "dsfsdhjkfasdhfs sdafasf fasdfsdaf sdffasdfsd a sdffasdf  fddsaf ffds asdffasd",
      "dasfd sdfasdfds  sdfasdf  sdfafsdf asdffsdf  sdffads",
    ],
    name: "Troubleshooter",
    eventCoordinators: [
      {
        name: "Shreya Dandapat",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1lpieo-tBY5SAK0zgRfVsYc0-IKtYmSzh",
        position: "event lead",
        phone: "8847850725",
        dept: "ME",
        year: "3rd",
        email: "sd2564@me.jgec.ac.in",
        isReverse: false,
      },
      {
        name: "Riddhiman Tarafder ",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1RsW0a4fwV0xTH--voF8tGEL_QwpVuWrs",
        position: "event coordinator",
        phone: "7384597900",
        dept: "ECE",
        year: "3rd",
        email: "rt2505@ece.jgec.ac.in",
        isReverse: true,
      },
      {
        name: "Shreya Dandapat",
        imgSrc:
          "https://drive.google.com/uc?export=view&id=1lpieo-tBY5SAK0zgRfVsYc0-IKtYmSzh",
        position: "event coordinator",
        phone: "8847850725",
        dept: "ME",
        year: "3rd",
        email: "sd2564@me.jgec.ac.in",
        isReverse: false,
      },
    ],
    videoSrc: "/Video/video.mp4",
    venue: "english lab Room",
    time: "Oct 3, 2023 12:00:00",
    register: "/events/sharkTankJolu/register",
    leaderboard: "/events/sharkTankJolu/leaderboard",
    prizes: [5000, 2000, 1000],
  },
];
